package myStore;// Generated by Selenium IDE

import PageObject.ChangeUserInfo.UserInfoPage;
import PageObject.LoginPage.LoginPage;
import PageObject.LoginPage.LoginPage2;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.Random;

public class CreateAccountTest {

  private WebDriver driver;
  LoginPage2 loginPage2;
  UserInfoPage userInfoPage;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "src/main/resources/drivers/geckodriver.exe");
    driver = new FirefoxDriver();
    driver.get("https://prod-kurs.coderslab.pl/index.php");

    loginPage2 = new LoginPage2(driver);
    userInfoPage=new UserInfoPage(driver);
  }

  @Test
  public void createAccount() {
    int limit = 1;
    for (int i=0; i < limit; i++) {
      driver.findElement(By.xpath("/html/body/main/header/nav/div/div/div[1]/div[2]/div[2]/div/a")).click();
      driver.findElement(By.linkText("No account? Create one here")).click();
      String name = generateString(5);
      driver.findElement(By.name("firstname")).sendKeys(name);

      driver.findElement(By.name("lastname")).sendKeys(generateString(7));
      String email = generateString(5)+"@"+generateString(10)+".pl";
      driver.findElement(By.name("email")).sendKeys(email);
      String password = generateString(5);
      driver.findElement(By.name("password")).sendKeys(password);
      driver.findElement(By.name("birthday")).sendKeys("01/01/2020");
      driver.findElement(By.cssSelector(".form-control-submit")).click();//save click

      try {
        System.out.println(driver.findElement(By.className("alert")).getText());
        Assert.fail("alert shouldn't appeared");
      } catch (NoSuchElementException e) {
        //all fine - Sign out
        driver.findElement(By.xpath("/html/body/main/header/nav/div/div/div[1]/div[2]/div[2]/div/a[1]")).click();
      }
      //try to login form+signin klik
      //loginPage2-Can Iuse it?
      driver.findElement(By.xpath("/html/body/main/header/nav/div/div/div[1]/div[2]/div[2]/div/a")).click();
      loginPage2.loginAs(email, password);


      //information Click
      //like a LoginPage2 for InformationPage
      //Informationclick
      userInfoPage.viewInformation();
      String text;


      //get data for everyfields
      String attributeFirstName= driver.findElement((By.name("firstname"))).getAttribute("value");
      //driver.findElements(By.name("firstname"))
      Assert.assertEquals(name,attributeFirstName);
      String attributeLastName = driver.findElement((By.name("lastname"))).getAttribute("value");
      //Assert.assertEquals(lastName,attributeLastName);
      //check form +assertion



      System.out.println("email: " + email + "; password: " + password);
    }

  }

  private String generateString(int length) {
    int leftLimit = 97; // letter 'a'
    int rightLimit = 122; // letter 'z'
    Random random = new Random();
    StringBuilder buffer = new StringBuilder(length);
    for (int i = 0; i < length; i++) {
      int randomLimitedInt = leftLimit + (int)(random.nextFloat() * (rightLimit - leftLimit + 1));
      buffer.append((char) randomLimitedInt);
    }
    return buffer.toString();
  }

  @After
  public void tearDown() {
//    driver.quit();
  }
}
